# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  
  
  Thank you and congrats🎉 for opening your very first issue in this project. CityonBikes is a Django based web app. 🛵
  If you have opened this issue with respect to SWOC 2021 then this issue will be closed as issues are only allowed to be opend by maintainer 😀
  Please adhere to our [Code of Conduct](https://github.com/preeti13456/CityonBikes/blob/master/CODE_OF_CONDUCT.md).
  
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  
  Thank you and congrats🎉 for opening your first pull request. CityonBikes is a Django based web app. 🛵  
  🙌🙌 We will get back to you as soon as we can 😄.
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀. 
